# Generated by Django 5.2 on 2025-04-04 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha programada')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, help_text='Observaciones internas', verbose_name='Notas')),
                ('calificacion', models.PositiveIntegerField(blank=True, help_text='De 1 a 5 estrellas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comentario', models.TextField(blank=True, help_text='Comentario del cliente', verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('jardinero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='servicios.jardinero', verbose_name='Jardinero')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='clientes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'indexes': [models.Index(fields=['fecha_programada'], name='agenda_cita_fecha_p_07c8fb_idx')],
            },
        ),
    ]
