# Generated by Django 5.2 on 2025-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jardinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('specialty', models.CharField(choices=[('pruning', 'Poda experta'), ('design', 'Diseño paisajístico'), ('maintenance', 'Mantenimiento integral'), ('irrigation', 'Sistemas de riego')], max_length=50, verbose_name='Especialidad')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Fecha de contratación')),
            ],
            options={
                'verbose_name': 'Jardinero',
                'verbose_name_plural': 'Jardineros',
            },
        ),
    ]
